import { ThemeOptions } from '@mui/material';

export default {
  light: {
    themeName: 'light',
    breakpoints: {
      values: {
        xs: 348,
        sm: 496,
        md: 720,
        lg: 1024,
        xl: 1200,
        xxl: 1472,
      },
    },
    components: {
      MuiCssBaseline: {
        styleOverrides: {
          body: {
            backgroundColor: '#f5f5f5',
          },
        },
      },
      MuiInputLabel: {
        styleOverrides: {
          asterisk: {
            display: 'none',
          },
        },
      },
      MuiPaper: {
        styleOverrides: {
          root: {
            backgroundColor: '#ffffff',
            borderWidth: 2,
            borderColor: '#d3d7db',
            borderRadius: 8,
          },
        },
      },
    },
    odb: {
      meta: {
        theme: {
          name: 'N30',
        },
        graphics: {
          hasBodyBackground: 'true',
        },
      },
      components: {
        alert: {
          type: 'filled',
        },
        button: {
          elevation: 0,
          font: {
            base: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.8750rem',
              lineHeight: '1.7150',
              letterSpacing: '0.0290rem',
              textTransform: 'uppercase',
            },
            sm: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.8125rem',
              lineHeight: '1.6930',
              letterSpacing: '0.0350rem',
              textTransform: 'uppercase',
            },
            lg: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.9375rem',
              lineHeight: '1.7340',
              letterSpacing: '0.0310rem',
              textTransform: 'uppercase',
            },
          },
          radius: 8,
          primary: {
            fill: '#66227D',
            on: '#ffffff',
            gradient: 'linear-gradient(90deg, #3075FB 0%, #66227D 100%)',
            type: 'filled',
          },
          secondary: {
            fill: '#66227D',
            on: '#ffffff',
            gradient: 'linear-gradient(90deg, #3075FB 0%, #66227D 100%)',
            type: 'outlined',
          },
          tertiary: {
            fill: '#66227D',
            on: '#ffffff',
            gradient: '#66227D',
            type: 'text',
          },
          destructive: {
            fill: '#b23224',
            on: '#ffffff',
            gradient: '#b23224',
            type: 'filled',
          },
        },
        dialog: {
          elevation: 0,
        },
        element: {
          borderColor: '#c0c1f6',
          borderWidth: 2,
          radius: 8,
        },
        divider: {
          line: '#d3d7db',
        },
        global: {
          elevation: {
            type: 'none',
          },
        },
        input: {
          type: 'standard',
        },
        lockScreen: {
          backgroundBlur: 10,
          fill: '#ffffffcc',
        },
        link: {
          color: '#3075FB',
          underline: 'hover',
        },
        mainNavigation: {
          elevation: 0,
          fill: '#4d49b8',
          gradient: 'linear-gradient(90deg, #3075FB 0%, #66227D 100%)',
          on: '#ffffff',
          active: '#6E9EFC',
          borderWidth: 0,
        },
        paper: {
          borderWidth: 2,
          borderColor: '#d3d7db',
          radius: 8,
          elevation: 0,
        },
        paymentCard: {
          elevation: 0,
        },
        segmentTitle: {
          color: '#66227D',
          colorGradient: 'linear-gradient(90deg, #3075FB 0%, #66227D 100%)',
          font: {
            fontFamily: 'Selawik, system-ui, sans-serif',
            fontWeight: 300,
            fontSize: '0.7500rem',
            lineHeight: '1.5000',
            letterSpacing: '0.0830rem',
            textTransform: 'uppercase',
          },
        },
        shortcut: {
          radius: 8,
          borderWidth: 2,
          elevation: 0,
        },
        splash: {
          fill: '#66227D',
        },
        stickyFooter: {
          visibility: 'true',
          gradient: '#ffffff',
          backgroundBlur: 0,
        },
        subtitle1: {
          font: {
            fontFamily: 'Selawik, system-ui, sans-serif',
            fontWeight: 300,
            fontSize: '1.0000rem',
            lineHeight: '1.7500',
            letterSpacing: '0.0090rem',
            textTransform: 'none',
          },
        },
        subtitle2: {
          font: {
            fontFamily: 'Selawik, system-ui, sans-serif',
            fontWeight: 400,
            fontSize: '0.8750rem',
            lineHeight: '1.5700',
            letterSpacing: '0.0070rem',
            textTransform: 'none',
          },
        },
      },
      graphics: {
        brand: {
          set: 'N30',
        },
        paymentCard: {
          set: 'Default',
        },
        icon: {
          set: 'N30',
          standard: '#66227D',
          neutral: '#636366',
          standardDisabled: '#66227d61',
          neutralDisabled: '#63636661',
        },
        illustrations: {
          set: 'N30',
        },
        schemeLogo: {
          set: 'Default',
        },
      },
      action: {
        active: {
          color: '#0000008a',
          opacityDec: 0.12,
        },
        disabled: {
          fill: '#0000001f',
          on: '#00000042',
          opacityDec: 0.38,
        },
        focus: {
          fill: '#0000001f',
          opacityDec: 0.12,
        },
        hover: {
          fill: '#0000000a',
          opacityDec: 0.04,
        },
        selected: {
          color: '#00000014',
          opacityDec: 0.08,
        },
      },
      background: {
        default: '#f5f5f5',
        surface: '#ffffff',
        element: '#f0effd',
        elementGradient: 'linear-gradient(90deg, #e8effb 0%, #fbefff 100%)',
      },
      tabBar: {
        fill: '#ffffff',
        on: '#636366',
        active: '#3075FB',
      },
      standard: {
        white: '#ffffff',
        whiteSemi: '#ffffff40',
        black: '#000000',
        blackSemi: '#00000040',
        main100: '#D1BDD8',
        main300: '#9464A4',
        main500: '#66227D',
        main700: '#53196A',
        main900: '#380C4D',
        main500Semi: '#66227d40',
        mainOn500: '#ffffff',
        accent100: '#a5bdee',
        accent300: '#6E9EFC',
        accent500: '#3075FB',
        accent700: '#2462FA',
        accent900: '#1345F8',
        accent500Semi: '#3075fb40',
        accentOn500: '#ffffff',
        grey50: '#FAFAFA',
        grey100: '#f5f5f5',
        grey200: '#F1F2F3',
        grey300: '#eceef0',
        grey400: '#E0E3E6',
        grey500: '#d3d7db',
        grey600: '#9B9DA1',
        grey700: '#636366',
        grey800: '#4B4B4D',
        grey900: '#323233',
      },
      semantic: {
        information100: '#dcf4fc',
        information300: '#88a4ad',
        information500: '#396777',
        information700: '#223e47',
        information900: '#172930',
        informationOn100: '#000000',
        informationOn300: '#000000',
        informationOn500: '#ffffff',
        information500Semi: '#39677740',
        negative100: '#ffe8e5',
        negative300: '#d1847c',
        negative500: '#b23224',
        negative700: '#6b1e16',
        negative900: '#350f0b',
        negativeOn100: '#000000',
        negativeOn300: '#000000',
        negativeOn500: '#ffffff',
        negative500Semi: '#b2322440',
        positive100: '#e6f7ed',
        positive300: '#9ab7a5',
        positive500: '#346f4b',
        positive700: '#1f432d',
        positive900: '#13281b',
        positiveOn100: '#000000',
        positiveOn300: '#000000',
        positiveOn500: '#ffffff',
        positive500Semi: '#346f4b40',
        warning100: '#fffddb',
        warning300: '#f7d277',
        warning500: '#f1b41d',
        warning700: '#916c11',
        warning900: '#533e04',
        warningOn100: '#000000',
        warningOn300: '#000000',
        warningOn500: '#000000',
        warning500Semi: '#f1b41d40',
      },
      typography: {
        set: 'N30',
        textPrimary: '#000000',
        textSecondary: '#636366',
        textDisabled: '#00000061',
        titlePrimary: '#66227D',
        titlePrimaryGradient: 'linear-gradient(90deg, #3075FB 0%, #66227D 100%)',
        textPrimaryInverse: '#ffffff',
        fontFamily: {
          body: 'Selawik',
          title: 'Selawik',
        },
        fontWeight: {
          regular: 300,
          medium: 400,
          strong: 700,
        },
        title: {
          base: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '2.1250rem',
              lineHeight: '1.2350',
              letterSpacing: '0.0070rem',
              textTransform: 'none',
            },
          },
          sm: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '1.5000rem',
              lineHeight: '1.3340',
              letterSpacing: '0.0000rem',
              textTransform: 'none',
            },
          },
          xs: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.2500rem',
              lineHeight: '1.6000',
              letterSpacing: '0.0080rem',
              textTransform: 'none',
            },
          },
        },
        body: {
          base: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
          },
          xl: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '2.1250rem',
              lineHeight: '1.2350',
              letterSpacing: '0.0025rem',
              textTransform: 'none',
            },
          },
          lg: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.2500rem',
              lineHeight: '1.6000',
              letterSpacing: '0.0015rem',
              textTransform: 'none',
            },
          },
          sm: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.8750rem',
              lineHeight: '1.5700',
              letterSpacing: '0.0070rem',
              textTransform: 'none',
            },
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '0.8750rem',
              lineHeight: '1.4300',
              letterSpacing: '0.0120rem',
              textTransform: 'none',
            },
          },
          xs: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '0.7500rem',
              lineHeight: '1.6600',
              letterSpacing: '0.0330rem',
              textTransform: 'none',
            },
          },
          xxs: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.6250rem',
              lineHeight: '1.4000',
              letterSpacing: '0.0000rem',
              textTransform: 'none',
            },
          },
        },
        mono: {
          base: {
            regular: {
              fontFamily: 'JetBrainsMono, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
            medium: {
              fontFamily: 'JetBrainsMono, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
          },
        },
      },
    },
    palette: {
      mode: 'light',
      common: {
        white: '#ffffff',
        black: '#000000',
      },
      odbPrimary: {
        main: '#66227D',
        light: '#66227D',
        dark: '#66227D',
        contrastText: '#ffffff',
      },
      odbSecondary: {
        main: '#66227D',
        light: '#66227D',
        dark: '#66227D',
        contrastText: '#ffffff',
      },
      odbTertiary: {
        main: '#66227D',
        light: '#66227D',
        dark: '#66227D',
        contrastText: '#ffffff',
      },
      odbDestructive: {
        main: '#b23224',
        light: '#b23224',
        dark: '#b23224',
        contrastText: '#ffffff',
      },
      primary: {
        main: '#66227D',
        light: '#9464A4',
        dark: '#53196A',
        contrastText: '#ffffff',
      },
      secondary: {
        main: '#3075FB',
        light: '#6E9EFC',
        dark: '#2462FA',
        contrastText: '#ffffff',
      },
      error: {
        main: '#b23224',
        light: '#d1847c',
        dark: '#6b1e16',
        contrastText: '#ffffff',
      },
      warning: {
        main: '#f1b41d',
        light: '#f7d277',
        dark: '#916c11',
        contrastText: '#000000',
      },
      info: {
        main: '#396777',
        light: '#88a4ad',
        dark: '#223e47',
        contrastText: '#ffffff',
      },
      success: {
        main: '#346f4b',
        light: '#9ab7a5',
        dark: '#1f432d',
        contrastText: '#ffffff',
      },
      grey: {
        '50': '#FAFAFA',
        '100': '#f5f5f5',
        '200': '#F1F2F3',
        '300': '#eceef0',
        '400': '#E0E3E6',
        '500': '#d3d7db',
        '600': '#9B9DA1',
        '700': '#636366',
        '800': '#4B4B4D',
        '900': '#323233',
        A100: '#f5f5f5',
        A200: '#F1F2F3',
        A400: '#E0E3E6',
        A700: '#636366',
      },
      contrastThreshold: 3,
      tonalOffset: 0.2,
      background: {
        paper: '#ffffff',
        default: '#f5f5f5',
      },
      text: {
        primary: '#000000',
        secondary: '#636366',
        disabled: '#00000061',
      },
      divider: '#d3d7db',
      action: {
        active: '#0000008a',
        hover: '#0000000a',
        hoverOpacity: 0.04,
        selected: '#00000014',
        selectedOpacity: 0.08,
        disabled: '#00000042',
        disabledBackground: '#0000001f',
        disabledOpacity: 0.38,
        focus: '#0000001f',
        focusOpacity: 0.12,
        activatedOpacity: 0.12,
      },
    },
    typography: {
      fontFamily: 'Selawik',
      sizes: {
        xs: '0.75rem',
        s: '0.875rem',
        m: '1rem',
        l: '1.5rem',
        xl: '2rem',
      },
      htmlFontSize: 16,
      fontSize: 15,
      fontWeightRegular: 300,
      fontWeightMedium: 400,
      fontWeightBold: 700,
      h1: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
      },
      h2: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
      },
      h3: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
      },
      h4: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '2.1250rem',
        lineHeight: '1.2350',
        letterSpacing: '0.0070rem',
      },
      h5: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.5000rem',
        lineHeight: '1.3340',
        letterSpacing: '0.0000rem',
      },
      h6: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '1.2500rem',
        lineHeight: '1.6000',
        letterSpacing: '0.0080rem',
      },
      subtitle1: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.0000rem',
        lineHeight: '1.7500',
        letterSpacing: '0.0090rem',
        textTransform: 'none',
      },
      subtitle2: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '0.8750rem',
        lineHeight: '1.5700',
        letterSpacing: '0.0070rem',
        textTransform: 'none',
      },
      body1: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.0000rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0090rem',
      },
      body2: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '0.8750rem',
        lineHeight: '1.4300',
        letterSpacing: '0.0120rem',
      },
      mono1: {
        fontFamily: 'JetBrainsMono, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '1.0000rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0090rem',
      },
      mono2: {
        fontFamily: 'JetBrainsMono, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.0000rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0090rem',
      },
      button: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '0.8750rem',
        lineHeight: '1.7150',
        letterSpacing: '0.0290rem',
        textTransform: 'uppercase',
      },
      caption: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '0.7500rem',
        lineHeight: '1.6600',
        letterSpacing: '0.0330rem',
      },
      overline: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '0.7500rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0830rem',
        textTransform: 'uppercase',
      },
    },
  },
  dark: {
    themeName: 'dark',
    breakpoints: {
      values: {
        xs: 348,
        sm: 496,
        md: 720,
        lg: 1024,
        xl: 1200,
        xxl: 1472,
      },
    },
    components: {
      MuiCssBaseline: {
        styleOverrides: {
          body: {
            backgroundColor: '#000000',
          },
        },
      },
      MuiInputLabel: {
        styleOverrides: {
          asterisk: {
            display: 'none',
          },
        },
      },
      MuiPaper: {
        styleOverrides: {
          root: {
            backgroundColor: '#1c1c1e',
            borderWidth: 2,
            borderColor: '#9a9da1',
            borderRadius: 8,
          },
        },
      },
    },
    odb: {
      meta: {
        theme: {
          name: 'N30',
        },
        graphics: {
          hasBodyBackground: 'true',
        },
      },
      components: {
        alert: {
          type: 'filled',
        },
        button: {
          elevation: 0,
          font: {
            base: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.8750rem',
              lineHeight: '1.7150',
              letterSpacing: '0.0290rem',
              textTransform: 'uppercase',
            },
            sm: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.8125rem',
              lineHeight: '1.6930',
              letterSpacing: '0.0350rem',
              textTransform: 'uppercase',
            },
            lg: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.9375rem',
              lineHeight: '1.7340',
              letterSpacing: '0.0310rem',
              textTransform: 'uppercase',
            },
          },
          radius: 8,
          primary: {
            fill: '#875E97',
            on: '#000000',
            gradient: 'linear-gradient(90deg, #6691FC 0%, #B391BE 100%)',
            type: 'filled',
          },
          secondary: {
            fill: '#875E97',
            on: '#ffffff',
            gradient: 'linear-gradient(90deg, #6691FC 0%, #B391BE 100%)',
            type: 'outlined',
          },
          tertiary: {
            fill: '#875E97',
            on: '#ffffff',
            gradient: '#875E97',
            type: 'text',
          },
          destructive: {
            fill: '#e25646',
            on: '#000000',
            gradient: '#e25646',
            type: 'filled',
          },
        },
        element: {
          borderColor: '#9a9bd8',
          borderWidth: 2,
          radius: 8,
        },
        dialog: {
          elevation: 0,
        },
        divider: {
          line: '#9a9da1',
        },
        global: {
          elevation: {
            type: 'none',
          },
        },
        input: {
          type: 'standard',
        },
        link: {
          color: '#6691FC',
          underline: 'hover',
        },
        lockScreen: {
          backgroundBlur: 10,
          fill: '#1c1c1ecc',
        },
        mainNavigation: {
          elevation: 0,
          fill: '#8e91dc',
          gradient: 'linear-gradient(90deg, #6691FC 0%, #B391BE 100%)',
          on: '#66227D',
          active: '#1345F8',
          borderWidth: 0,
        },
        paper: {
          borderWidth: 2,
          borderColor: '#9a9da1',
          radius: 8,
          elevation: 0,
        },
        paymentCard: {
          elevation: 0,
        },
        segmentTitle: {
          color: '#B391BE',
          colorGradient: 'linear-gradient(90deg, #6691FC 0%, #B391BE 100%)',
          font: {
            fontFamily: 'Selawik, system-ui, sans-serif',
            fontWeight: 300,
            fontSize: '0.7500rem',
            lineHeight: '1.5000',
            letterSpacing: '0.0830rem',
            textTransform: 'uppercase',
          },
        },
        shortcut: {
          radius: 8,
          borderWidth: 2,
          elevation: 0,
        },
        splash: {
          fill: '#66227D',
        },
        stickyFooter: {
          visibility: 'true',
          gradient: '#1c1c1e',
          backgroundBlur: 0,
        },
        subtitle1: {
          font: {
            fontFamily: 'Selawik, system-ui, sans-serif',
            fontWeight: 300,
            fontSize: '1.0000rem',
            lineHeight: '1.7500',
            letterSpacing: '0.0090rem',
            textTransform: 'none',
          },
        },
        subtitle2: {
          font: {
            fontFamily: 'Selawik, system-ui, sans-serif',
            fontWeight: 400,
            fontSize: '0.8750rem',
            lineHeight: '1.5700',
            letterSpacing: '0.0070rem',
            textTransform: 'none',
          },
        },
      },
      graphics: {
        brand: {
          set: 'N30',
        },
        paymentCard: {
          set: 'Default',
        },
        icon: {
          set: 'N30',
          standard: '#B391BE',
          neutral: '#9a9da1',
          standardDisabled: '#b391be61',
          neutralDisabled: '#9a9da161',
        },
        illustrations: {
          set: 'N30',
        },
        schemeLogo: {
          set: 'Default',
        },
      },
      action: {
        active: {
          color: '#ffffff',
          opacityDec: 0.24,
        },
        disabled: {
          fill: '#ffffff1f',
          on: '#00000042',
          opacityDec: 0.38,
        },
        focus: {
          fill: '#ffffff1f',
          opacityDec: 0.12,
        },
        hover: {
          fill: '#ffffff14',
          opacityDec: 0.08,
        },
        selected: {
          color: '#00000029',
          opacityDec: 0.16,
        },
      },
      background: {
        default: '#000000',
        surface: '#1c1c1e',
        element: '#392c7c',
        elementGradient: 'linear-gradient(90deg, #183d7d 0%, #61177a 100%)',
      },
      tabBar: {
        fill: '#1c1c1e',
        on: '#9a9da1',
        active: '#6691FC',
      },
      standard: {
        white: '#ffffff',
        whiteSemi: '#ffffff40',
        black: '#000000',
        blackSemi: '#00000040',
        main100: '#66227D',
        main300: '#875E97',
        main500: '#B391BE',
        main700: '#CAB2D2',
        main900: '#E8DEEC',
        main500Semi: '#c6acce',
        mainOn500: '#000000',
        accent100: '#1345F8',
        accent300: '#6691FC',
        accent500: '#98BAFD',
        accent700: '#B7CFFE',
        accent900: '#E0EAFE',
        accent500Semi: '#6691fc40',
        accentOn500: '#000000',
        grey50: '#0F0F10',
        grey100: '#1c1c1e',
        grey200: '#2B2B2D',
        grey300: '#3a3a3c',
        grey400: '#525356',
        grey500: '#6a6c6f',
        grey600: '#828588',
        grey700: '#9a9da1',
        grey800: '#C8CACC',
        grey900: '#f5f6f7',
      },
      semantic: {
        information100: '#1d282c',
        information300: '#3a5058',
        information500: '#618592',
        information700: '#90aab3',
        information900: '#dcf4fc',
        informationOn100: '#f5f6f7',
        informationOn300: '#f5f6f7',
        informationOn500: '#000000',
        information500Semi: '#61859240',
        negative100: '#441a15',
        negative300: '#88342a',
        negative500: '#e25646',
        negative700: '#ee9a90',
        negative900: '#ffe8e5',
        negativeOn100: '#f5f6f7',
        negativeOn300: '#f5f6f7',
        negativeOn500: '#000000',
        negative500Semi: '#e2564640',
        positive100: '#1f432d',
        positive300: '#346f4b',
        positive500: '#9ab7a5',
        positive700: '#c2d4c9',
        positive900: '#e6f7ed',
        positiveOn100: '#f5f6f7',
        positiveOn300: '#f5f6f7',
        positiveOn500: '#000000',
        positive500Semi: '#9ab7a540',
        warning100: '#533e04',
        warning300: '#916c11',
        warning500: '#f1b41d',
        warning700: '#f7d277',
        warning900: '#fffddb',
        warningOn100: '#f5f6f7',
        warningOn300: '#f5f6f7',
        warningOn500: '#000000',
        warning500Semi: '#f1b41d40',
      },
      typography: {
        set: 'N30',
        textPrimary: '#f5f6f7',
        textSecondary: '#9a9da1',
        textDisabled: '#f5f6f761',
        titlePrimary: '#B391BE',
        titlePrimaryGradient: 'linear-gradient(90deg, #6691FC 0%, #B391BE 100%)',
        textPrimaryInverse: '#000000',
        fontFamily: {
          body: 'Selawik',
          title: 'Selawik',
        },
        fontWeight: {
          regular: 300,
          medium: 400,
          strong: 700,
        },
        title: {
          base: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '2.1250rem',
              lineHeight: '1.2350',
              letterSpacing: '0.0070rem',
              textTransform: 'none',
            },
          },
          sm: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '1.5000rem',
              lineHeight: '1.3340',
              letterSpacing: '0.0000rem',
              textTransform: 'none',
            },
          },
          xs: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.2500rem',
              lineHeight: '1.6000',
              letterSpacing: '0.0080rem',
              textTransform: 'none',
            },
          },
        },
        body: {
          base: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
          },
          xl: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '2.1250rem',
              lineHeight: '1.2350',
              letterSpacing: '0.0025rem',
              textTransform: 'none',
            },
          },
          lg: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.2500rem',
              lineHeight: '1.6000',
              letterSpacing: '0.0015rem',
              textTransform: 'none',
            },
          },
          sm: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.8750rem',
              lineHeight: '1.5700',
              letterSpacing: '0.0070rem',
              textTransform: 'none',
            },
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '0.8750rem',
              lineHeight: '1.4300',
              letterSpacing: '0.0120rem',
              textTransform: 'none',
            },
          },
          xs: {
            regular: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '0.7500rem',
              lineHeight: '1.6600',
              letterSpacing: '0.0330rem',
              textTransform: 'none',
            },
          },
          xxs: {
            medium: {
              fontFamily: 'Selawik, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '0.6250rem',
              lineHeight: '1.4000',
              letterSpacing: '0.0000rem',
              textTransform: 'none',
            },
          },
        },
        mono: {
          base: {
            regular: {
              fontFamily: 'JetBrainsMono, system-ui, sans-serif',
              fontWeight: 300,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
            medium: {
              fontFamily: 'JetBrainsMono, system-ui, sans-serif',
              fontWeight: 400,
              fontSize: '1.0000rem',
              lineHeight: '1.5000',
              letterSpacing: '0.0090rem',
              textTransform: 'none',
            },
          },
        },
      },
    },
    palette: {
      mode: 'dark',
      common: {
        white: '#ffffff',
        black: '#000000',
      },
      odbPrimary: {
        main: '#875E97',
        light: '#875E97',
        dark: '#875E97',
        contrastText: '#000000',
      },
      odbSecondary: {
        main: '#875E97',
        light: '#875E97',
        dark: '#875E97',
        contrastText: '#ffffff',
      },
      odbTertiary: {
        main: '#875E97',
        light: '#875E97',
        dark: '#875E97',
        contrastText: '#ffffff',
      },
      odbDestructive: {
        main: '#e25646',
        light: '#e25646',
        dark: '#e25646',
        contrastText: '#000000',
      },
      primary: {
        main: '#B391BE',
        light: '#CAB2D2',
        dark: '#875E97',
        contrastText: '#000000',
      },
      secondary: {
        main: '#98BAFD',
        light: '#B7CFFE',
        dark: '#6691FC',
        contrastText: '#000000',
      },
      error: {
        main: '#e25646',
        light: '#ee9a90',
        dark: '#88342a',
        contrastText: '#000000',
      },
      warning: {
        main: '#f1b41d',
        light: '#f7d277',
        dark: '#916c11',
        contrastText: '#000000',
      },
      info: {
        main: '#618592',
        light: '#90aab3',
        dark: '#3a5058',
        contrastText: '#000000',
      },
      success: {
        main: '#9ab7a5',
        light: '#c2d4c9',
        dark: '#346f4b',
        contrastText: '#000000',
      },
      grey: {
        '50': '#f5f6f7',
        '100': '#C8CACC',
        '200': '#9a9da1',
        '300': '#828588',
        '400': '#6a6c6f',
        '500': '#525356',
        '600': '#3a3a3c',
        '700': '#2B2B2D',
        '800': '#1c1c1e',
        '900': '#0F0F10',
        A100: '#C8CACC',
        A200: '#9a9da1',
        A400: '#6a6c6f',
        A700: '#2B2B2D',
      },
      contrastThreshold: 3,
      tonalOffset: 0.2,
      background: {
        paper: '#1c1c1e',
        default: '#000000',
      },
      text: {
        primary: '#f5f6f7',
        secondary: '#9a9da1',
        disabled: '#f5f6f761',
      },
      divider: '#9a9da1',
      action: {
        active: '#ffffff',
        hover: '#ffffff14',
        hoverOpacity: 0.08,
        selected: '#00000029',
        selectedOpacity: 0.16,
        disabled: '#00000042',
        disabledBackground: '#ffffff1f',
        disabledOpacity: 0.38,
        focus: '#ffffff1f',
        focusOpacity: 0.12,
        activatedOpacity: 0.24,
      },
    },
    typography: {
      fontFamily: 'Selawik',
      sizes: {
        xs: '0.75rem',
        s: '0.875rem',
        m: '1rem',
        l: '1.5rem',
        xl: '2rem',
      },
      htmlFontSize: 16,
      fontSize: 15,
      fontWeightRegular: 300,
      fontWeightMedium: 400,
      fontWeightBold: 700,
      h1: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
      },
      h2: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
      },
      h3: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
      },
      h4: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '2.1250rem',
        lineHeight: '1.2350',
        letterSpacing: '0.0070rem',
      },
      h5: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.5000rem',
        lineHeight: '1.3340',
        letterSpacing: '0.0000rem',
      },
      h6: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '1.2500rem',
        lineHeight: '1.6000',
        letterSpacing: '0.0080rem',
      },
      subtitle1: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.0000rem',
        lineHeight: '1.7500',
        letterSpacing: '0.0090rem',
        textTransform: 'none',
      },
      subtitle2: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '0.8750rem',
        lineHeight: '1.5700',
        letterSpacing: '0.0070rem',
        textTransform: 'none',
      },
      body1: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.0000rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0090rem',
      },
      body2: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '0.8750rem',
        lineHeight: '1.4300',
        letterSpacing: '0.0120rem',
      },
      mono1: {
        fontFamily: 'JetBrainsMono, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '1.0000rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0090rem',
      },
      mono2: {
        fontFamily: 'JetBrainsMono, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '1.0000rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0090rem',
      },
      button: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 400,
        fontSize: '0.8750rem',
        lineHeight: '1.7150',
        letterSpacing: '0.0290rem',
        textTransform: 'uppercase',
      },
      caption: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '0.7500rem',
        lineHeight: '1.6600',
        letterSpacing: '0.0330rem',
      },
      overline: {
        fontFamily: 'Selawik, system-ui, sans-serif',
        fontWeight: 300,
        fontSize: '0.7500rem',
        lineHeight: '1.5000',
        letterSpacing: '0.0830rem',
        textTransform: 'uppercase',
      },
    },
  },
} as Record<'light' | 'dark', ThemeOptions>;
